# -*- coding: utf-8 -*-
"""value_investing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCv2T2ZTfBrIVrR1XIDtMG29veoKTR0I
"""

import pandas as pd
import numpy as np
import yfinance as yf
import math
from scipy import stats

tickers=pd.read_csv("/content/datamd.csv")

tickers

def fetch_values_of_stocks(tickers):

    value_cols = [
        "Ticker",
        "Price",
        "PE-Ratio",
        "PB-Ratio",
        "PS-Ratio",
        "EV/EBITDA",
        "EV/GP"
    ]

    value_df = pd.DataFrame(columns=value_cols)
    for ticker in tickers:
        stock = yf.Ticker(ticker)
        price = stock.history(period = "1d")['Close'].iloc[-1]

        financials = stock.financials
        balanceSheet = stock.balance_sheet
        cashflow = stock.cashflow

        pe_ratio = stock.info.get("forwardPE", np.nan)
        pb_ratio = stock.info.get("priceToBook", np.nan)
        ps_ratio = stock.info.get("priceToSalesTrailing12Months", np.nan)
        ev = stock.info.get("enterpriseValue", np.nan)
        ebitda = stock.info.get("ebitda", np.nan)
        evEbitda = ev / ebitda if ev and ebitda else np.nan
        grossProfit = stock.info.get("grossMargins", np.nan) * stock.info.get("totalRevenue", np.nan)
        evGrossProfit = ev / grossProfit if ev and grossProfit else np.nan

        value_df.loc[len(value_df)] = [
            ticker,
            price,
            pe_ratio,
            pb_ratio,
            ps_ratio,
            evEbitda,
            evGrossProfit
          ]
    return value_df

ticker=tickers['Ticker'].values.tolist();
df=fetch_values_of_stocks(ticker)
df

val_cols=[
    "PE-Ratio",
        "PB-Ratio",
        "PS-Ratio",
        "EV/EBITDA",
        "EV/GP"
]
for col in val_cols:
  df[col]=df[col].fillna(df[col].mean())
df.info()

percentile={
    "PE-Ratio":"PER percentile",
    "PB-Ratio":"PBR percentile",
    "PS-Ratio":"PSR percentile",
    "EV/EBITDA":"EV/EBITDAR percentile",
    "EV/GP":"EV/GPR percentile"
}
for metric,percent in percentile.items():
  df[percent]=df[metric].apply(lambda x:stats.percentileofscore(df[metric],x)/100)
df.head()

from statistics import mean

df['Value_Score']=df[[value for value in percentile.values()]].mean(axis=1)

df

df=df.sort_values(by='Value_Score',ascending=False)

df.head(10)